export const ADD_NOMINEE = 'ADD_NOMINEE';
export const ADD_CURRENT_NOMINEES = 'ADD_CURRENT_NOMINEESS';
export const REMOVE_NOMINEE = 'REMOVE_NOMINEE';
export const GET_RESULTS = 'GET_RESULTS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const NOMINATIONS_COMPLETE = 'NOMINATIONS_COMPLETE';
